#
# SEE:
# https://fangpenlin.com/posts/2014/08/11/building-docker-image-with-ansible/
# http://docs.ansible.com/ansible/docker_module.html
# https://github.com/ansible/ansible/blob/devel/docsite/rst/guide_docker.rst

---
- name: Build happn-cluster app image
  hosts: all
  sudo: no
  vars_prompt:
    - name: happn_cluster_version
      prompt: "happn_cluster_version"
      default: "1.0.0"
      private: no
    - name: happn_cluster_iteration
      prompt: "happn_cluster_iteration"
      default: 1
      private: no
    - name: mongo_url
      prompt: "mongo_url"
      default: "mongodb://0.0.0.0:27017/happn-cluster-test"
      private: no
    - name: mongo_collection
      prompt: "mongo_collection"
      default: "happn_cluster_test"
      private: no
#  vars: # cluster members deployed on each entry in the
#    - happn_cluster_config: "{{ lookup('file', 'cluster_config.json') | from_json }}"
#    - custer_members:
#      - {id: 1, host: "{{inventory_hostname}}", port: "60000:60000"}
#      - {id: 2, host: "{{inventory_hostname}}", port: "60001:60001"}
#      - {id: 3, host: "{{inventory_hostname}}", port: "60002:60002"}
  roles:
    - { role: cluster_image_build, dir: "{{base_path}}/examples/happn-cluster/deploy/multi_host_single_container/roles/cluster_image_build" }

