
- name: gather network info for all hosts
  hosts: all
  pre_tasks:
    - name: 'get the parent directory'
      command: lookup('pipe','cd ../ && pwd') | string
      register: parent_dir
    - name: 'set roles directory variable'
      command: "{{parent_dir}}/roles"
      register: roles_dir

- include: cluster-info.yml # gather all network info for the hosts
- include: happn-cluster.yml  # main cluster build