
- name: gather network info for all hosts
  hosts: all
  vars:
    - parent_dir: "{{ lookup('pipe','cd ../ && pwd') | string }}"
  tasks:
    - name: 'parent directory debug'
      debug:
        msg: "Parent: {{ parent_dir }}"

- include: cluster-info.yml # gather all network info for the hosts
  vars: parent_dir="{{ parent_dir }}"

- include: happn-cluster.yml # main cluster build
  vars: parent_dir="{{ parent_dir }}"