
- name: gather network info for all hosts
  hosts: all
  tasks:
    - name: 'set roles path variable'
      set_fact: roles_dir="{{ lookup('pipe','cd ../ && pwd`') }}/roles"
    - name: 'show roles path'
      debug:
          msg: "Roles dir: {{ roles_dir }}"

- include: cluster-info.yml # gather all network info for the hosts
- include: happn-cluster.yml  # main cluster build