
- name: gather network info for all hosts
  hosts: all
#  vars:
#    - parent_dir: "{{ lookup('pipe','cd ../ && pwd') | string }}"
#  tasks:
#    - set_fact:
#        parent_dir: "{{ lookup('pipe','cd ../ && pwd') | string }}"
#    - name: 'parent directory debug'
#      debug:
#        msg: "Parent: {{ parent_dir }}"

# gather all network info for the hosts
- include: cluster-info.yml

# main cluster build
- include: happn-cluster.yml