
- name: Set some variables
  hosts: all
  vars:
    - parent_dir: "{{ lookup('pipe','cd ../ && pwd') | string }}"
  tasks:
    - name: 'parent directory debug'
      debug:
        msg: "Parent: {{ parent_dir }}"