
- name: Set some variables
  hosts: all
  vars:
    parent_dir: "{{lookup('pipe','cd ../ && pwd') | string}}"
#  tasks:
#    - name: 'set var'
#      set_fact:
#        parent_dir: "{{lookup('pipe','cd ../ && pwd') | string}}"