
- name: Set some variables
  hosts: all

  tasks:
    - name: 'get the parent directory'
      command: lookup('pipe','cd ../ && pwd') | string
      register: parent_dir

  vars:
    roles_dir: "{{parent_dir}}/roles"