
- name: Set some variables
  hosts: all

  tasks:
    - name: 'get the parent directory'
      command: lookup('pipe','cd ../ && pwd') | string
      register: parent_dir
    - name: 'set roles dir'
      set_fact:
        roles_dir: "{{parent_dir}}/roles"
    - name: 'display vars'
      debug:
        msg: 'Roles dir {{roles_dir}}'