
- name: Gather all hosts info
  hosts: all  # this ensures that the playbook is run against ALL hosts before moving to the next playbook
  vars:
    - parent_dir: "{{ lookup('pipe','cd ../ && pwd') | string }}" # dynamically find the parent directory
  vars_files:
    - "{{ parent_dir }}/group_vars/all"
  roles:
    - role: "{{ parent_dir }}/roles/cluster_information"