
- name: gather network info for all hosts
  hosts: all
  vars:
    - happn_cluster_ip_info: []
    - happn_cluster_seed_port: 57000

# gather all network info for the hosts
- include: cluster-info.yml

# main cluster build
- include: happn-cluster.yml