- assert:
    that:
      - 'happn_cluster_version != ""'

- name: install apt packages
  apt: "name='{{ item }}' state=present"
  with_items:
    - git
    - python-pip

- name: install docker-py
  pip: name=docker-py version=1.7.0 state=present

- name: create build directory
  file: >
    dest="{{ happn_cluster_build_dir }}"
    state=directory

### clone the Github repo
- name: clone happn-cluster git repo
  git: >
    repo="{{ happn_cluster_repo }}"
    dest="{{ happn_cluster_build_dir }}/happn_cluster"
   # version="v{{ happn_cluster_version }}"
  register: happn_cluster_repo

- name: remove git deploy key
  file: dest=/tmp/github_deploy_key state=absent

#- name: archive repo
#  shell: >
#    cd "{{ happn_cluster_build_dir }}/{{ item }}" &&
#    git archive -o ../{{ item }}.tar HEAD
#  with_items:
#    - happn_cluster

- name: archive repo
  shell: >
    cd "{{ happn_cluster_build_dir }}/{{ item }}/happn_cluster/app" &&
    git archive -o ../{{ item }}.tar HEAD
  with_items:
    - happn_cluster

- name: generate templates
  template: >
    src="{{ item.src }}"
    dest="{{ happn_cluster_build_dir }}/{{ item.dest }}"
  with_items:
    - { src: "Dockerfile", dest: "Dockerfile" }
    #- { src: "runapp.sh", dest: "runapp.sh" }

- name: build image
  docker_image: >
    name="{{ happn_cluster_image_name }}"
    tag="{{ happn_cluster_image_tag }}"
    path="{{ happn_cluster_build_dir }}"
    state=build

- name: tag
  command: >
    docker tag
    {{ happn_cluster_image_name }}:{{ happn_cluster_image_tag }}
    {{ happn_cluster_image_name }}:{{ happn_cluster_extra_tag }}
  when: happn_cluster_extra_tag != ''

# create a container for each member in happn_cluster_members
- name: run happn-cluster
  docker_container:
    name: "node_{{item.id}}"
    image: "{{ happn_cluster_image_name }}:{{ happn_cluster_extra_tag }}"
    published_ports: "{{ item.port }}"
    env:
      MONGO_URL: "{{ happn_cluster_mongo_url }}"
      MONGO_COLLECTION: "{{ happn_cluster_mongo_collection }}"
      PORT_MAPPING: "{{item.port}}"
      HOST: "{{item.host}}"
      CLUSTER_MEMBERS: "{{happn_cluster_members}}"
  with_items: "{{happn_cluster_members}}"
