- assert:
    that:
      - 'mongo_instance_version != ""'

- name: create build directory
  file: >
    dest="{{ mongo_instance_build_dir }}"
    state=directory

- name: generate templates
  template: >
    src="{{ item.src }}"
    dest="{{ mongo_instance_build_dir }}/{{ item.dest }}"
  with_items:
    - { src: "Dockerfile", dest: "Dockerfile" }

- name: build image
  docker_image: >
    name="{{ mongo_instance_image_name }}"
    tag="{{ mongo_instance_image_tag }}"
    path="{{ mongo_instance_build_dir }}"
    state=build

- name: tag
  command: >
    docker tag
    {{ mongo_instance_image_name }}:{{ mongo_instance_image_tag }}
    {{ mongo_instance_image_name }}:{{ mongo_instance_extra_tag }}
  when: mongo_instance_extra_tag != ''

# create a container for each member in happn_cluster_members
- name: run mongo_instance
  docker_container:
    name: "mongo-instance"
    image: "{{ mongo_instance_image_name }}:{{ mongo_instance_extra_tag }}"
    published_ports: "{{ ports }}"
