
# get the internal IP of the cloud instance (eg: EC2)
- name: get instance internal IP
  shell: >
    ifconfig eth | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}'
  register: current_ip

- name: show ip
  debug:
    msg: "Current internal IP - {{current_ip.stdout}}"

- name: create list item
  vars:
    current_entry: {external: "", internal: "", port: ""}
  set_fact:
    current_entry:
      external: "{{inventory_hostname}}"
      internal: "{{current_ip.stdout}}"
      port: "{{happn_cluster_seed_port}}"

- name: add item to list
  set_fact:
    happn_cluster_ip_info: "{{ happn_cluster_ip_info | union([current_entry])}}"

- name: increment port
#  set_fact:
#    happn_cluster_seed_port: "{{ happn_cluster_seed_port | int + 1 }}"
  local_action: shell file=$((`cat /tmp/host_num` + 1)); echo $file | tee /tmp/host_num
  register: host_num

- name: Set host number
  command: 'touch file{{ host_num.stdout }}'

- name:as
  set_fact:
    happn_cluster_seed_port: "{{host_num | int}}"

- name: show current port number
  debug:
    msg: "Current port number - {{happn_cluster_seed_port}}"