
- name: populate array of happn_cluster_ip_info
  set_fact:
    happn_cluster_ip_info: "{{ happn_cluster_ip_info | union([hostvars[item]['ansible_default_ipv4']['address'] + ':' + (happn_cluster_seed_port | string)])}}"
  with_items: "{{ groups['all'] }}"

- name: show ip list
  debug:
    msg: "IP list - {{happn_cluster_ip_info}}"

#- name: increment port
#  set_fact:
#    happn_cluster_seed_port: "{{ happn_cluster_seed_port | int + 1 }}"
#
#- name: show current port number
#  debug:
#    msg: "Current port number - {{happn_cluster_seed_port}}"
