- assert:
    that:
      - 'happn_cluster_version != ""'

- name: show cluster info gathered from previous playbook
  debug:
    msg: "Info - {{happn_cluster_ip_info}}"

- name: set happn_cluster_config vars
  set_fact:
    happn_cluster_config: "{{ lookup('file', '../templates/cluster_config.json') | string }}"
    happn_cluster_app_dir: "{{ happn_cluster_build_dir }}/happn_cluster/examples/happn-cluster/app"

- name: create temp vars
  set_fact:
    counter: 0
    current_seed: false
    current_internal_ip: ""
    current_port: ""
    current_entry: ""

- name: create member array
  set_fact:
    happn_cluster_members: "{{ happn_cluster_members | union([item.internal + ':' + (item.port | string)])}}"
  with_items: "{{happn_cluster_ip_info}}"

- name: pull out details for the current host
  set_fact:
    current_seed : "{{counter == 0 | bool}}"
    counter : "{{counter + 1 | int}}"
    current_internal_ip : "{{item.internal}}"
    current_port : "{{item.port}}"
    current_entry: "{{item.internal + ':' + (item.port | string)}}"
  when: "{{inventory_hostname == item.external}}"
  with_items: "{{happn_cluster_ip_info}}"

- name: inject variables into happn_cluster_config
  set_fact:
    happn_cluster_config: "{{ happn_cluster_config
    | replace('\"#seed\"', (current_seed | string))
    | replace('\"#hosts\"', (happn_cluster_members | to_json))
    | replace('#announceHost', (current_internal_ip | string))
    | replace('\"#port\"', (current_port | string))
    | replace('#mongoCollection', (happn_cluster_mongo_collection | string))
    | replace('#mongoUrl', (happn_cluster_mongo_url | string)) }}"

- name: show cluster config
  debug:
      msg: "CONFIG - {{ happn_cluster_config }}"

- name: install apt packages
  apt: "name='{{ item }}' state=present"
  with_items:
    - git
    - python-pip

- name: install docker-py
  pip: name=docker-py version=1.7.0 state=present

- name: create build directory
  file: >
    dest="{{ happn_cluster_build_dir }}"
    state=directory

### clone the Github repo
- name: clone happn-cluster git repo
  git: >
    repo="{{ happn_cluster_repo }}"
    dest="{{ happn_cluster_build_dir }}/happn_cluster"
   # version="v{{ happn_cluster_version }}"
  register: happn_cluster_repo

- name: remove git deploy key
  file: dest=/tmp/github_deploy_key state=absent

- name: copy new config to app directory
  copy:
    content: "{{ happn_cluster_config }}"
    dest: "{{ happn_cluster_app_dir }}/cluster_config.json"

#- name: archive repo
#  shell: >
#    cd "{{ happn_cluster_build_dir }}/{{ item }}" &&
#    git archive -o ../{{ item }}.tar HEAD
#  with_items:
#    - happn_cluster

- name: archive repo
  shell: >
    tar -cvf "{{ happn_cluster_build_dir }}/happn-cluster.tar" --exclude .git -C "{{ happn_cluster_build_dir }}" happn_cluster

- name: generate templates
  template: >
    src="{{ item.src }}"
    dest="{{ happn_cluster_build_dir }}/{{ item.dest }}"
  with_items:
    - { src: "Dockerfile", dest: "Dockerfile" }

- name: build image
  docker_image: >
    name="{{ happn_cluster_image_name }}"
    tag="{{ happn_cluster_image_tag }}"
    path="{{ happn_cluster_build_dir }}"
    state=build

- name: tag
  command: >
    docker tag
    {{ happn_cluster_image_name }}:{{ happn_cluster_image_tag }}
    {{ happn_cluster_image_name }}:{{ happn_cluster_extra_tag }}
  when: happn_cluster_extra_tag != ''

# create a container
- name: run happn-cluster
  docker_container:
#    name: "node_{{item.id}}"
    name: "node_x"
    image: "{{ happn_cluster_image_name }}:{{ happn_cluster_extra_tag }}"
    published_ports: "{{current_port}}:{{current_port}}"


