FROM ubuntu:14.04
MAINTAINER ig-grant

# Declare args
ARG NVM_DIR=$HOME/.nvm
ARG NVM_VERSION=0.32.0
ARG NODE_VERSION=4.6.2

#### General ####
RUN apt-get update && apt-get install -y curl wget git git-core curl build-essential

#### Install NVM (Node Version Manager) ####

# Replace sh with bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install nvm with node and npm
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.0/install.sh | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# Set up our PATH correctly so we don't have to long-reference npm, node, &c.
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

## Create cluster dir and install packages
RUN mkdir -p home/happn-cluster
RUN cd home/happn-cluster

COPY happn_cluster.tar .
RUN tar -xvf happn_cluster.tar
RUN echo "{{ happn_cluster_image_tag }}" > /home/happn-cluster/version.txt
RUN echo "{{ happn_cluster_repo.after }}" > /home/happn-cluster/git_revision.txt

# Install npm dependencies
RUN cd /home/happn-cluster/examples/happn-cluster/app && npm install

#ADD "{{ happn_cluster_app_dir }}/cluster_config.json" /home/happn-cluster/examples/happn-cluster/app

### Set up working directory
WORKDIR /home/happn-cluster/examples/happn-cluster/app

#CMD node server
CMD ["/bin/bash"]

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*